<!-- <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet" /> -->

<?php
@session_start();
if (isset($_SESSION["Auth"])) {
  if ($_SESSION["Auth"]["role"] === '1') {
    $controller = $this->datacrypt('home');
    $action = $this->datacrypt('newview-home');
    $url = "?goto=$controller&action=$action";
    header("Location:/$url");
  }
} else {
  $controller = $this->datacrypt('home');
  $action = $this->datacrypt('newview-home');
  $url = "?goto=$controller&action=$action";
  header("Location:/$url");
}
?>
<style>
  .active{
    background-color:#3798A6 ;
  }
</style>
<!-- Desktop sidebar -->
<aside class="z-20 flex-shrink-0 hidden w-64 pl-4 overflow-y-auto bg-white dark:bg-gray-800 md:block">
  <div class="text-gray-500 dark:text-gray-400">
    <div class="flex items-center mt-6 ml-4 ">
      <!-- <img style="width: 100px; height:100px; margin-left:20px" src="ressources/images/logo_mastercode.png"
        alt="logo_mastercode"> -->
      <a href="#" class="text-xl font-bold flex items-center gap-1 lg:ml-2.5">
        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0,0,256,256" width="35px" height="35px" fill-rule="nonzero">
          <g fill="none" fill-rule="nonzero" stroke="none" stroke-width="1" stroke-linecap="butt" stroke-linejoin="miter" stroke-miterlimit="10" stroke-dasharray="" stroke-dashoffset="0" font-family="none" font-weight="none" font-size="none" text-anchor="none" style="mix-blend-mode: normal">
            <g transform="scale(3.2,3.2)">
              <path d="M42,75.5c-19.575,0 -35.5,-15.925 -35.5,-35.5c0,-19.575 15.925,-35.5 35.5,-35.5c19.575,0 35.5,15.925 35.5,35.5c0,19.575 -15.925,35.5 -35.5,35.5zM42,15.5c-13.509,0 -24.5,10.991 -24.5,24.5c0,13.509 10.991,24.5 24.5,24.5c13.509,0 24.5,-10.991 24.5,-24.5c0,-13.509 -10.991,-24.5 -24.5,-24.5z" fill="#3798A6"></path>
              <path d="M42,5c19.299,0 35,15.701 35,35c0,19.299 -15.701,35 -35,35c-19.299,0 -35,-15.701 -35,-35c0,-19.299 15.701,-35 35,-35M42,65c13.785,0 25,-11.215 25,-25c0,-13.785 -11.215,-25 -25,-25c-13.785,0 -25,11.215 -25,25c0,13.785 11.215,25 25,25M42,4c-19.882,0 -36,16.118 -36,36c0,19.882 16.118,36 36,36c19.882,0 36,-16.118 36,-36c0,-19.882 -16.118,-36 -36,-36zM42,64c-13.255,0 -24,-10.745 -24,-24c0,-13.255 10.745,-24 24,-24c13.255,0 24,10.745 24,24c0,13.255 -10.745,24 -24,24z" fill="#3798A6"></path>
              <path d="M58,27.5c-6.341,0 -11.5,-5.159 -11.5,-11.5c0,-6.341 5.159,-11.5 11.5,-11.5c6.341,0 11.5,5.159 11.5,11.5c0,6.341 -5.159,11.5 -11.5,11.5z" fill="#3798A6"></path>
              <path d="M58,5c6.065,0 11,4.935 11,11c0,6.065 -4.935,11 -11,11c-6.065,0 -11,-4.935 -11,-11c0,-6.065 4.935,-11 11,-11M58,4c-6.627,0 -12,5.373 -12,12c0,6.627 5.373,12 12,12c6.627,0 12,-5.373 12,-12c0,-6.627 -5.373,-12 -12,-12z" fill="#3798A6"></path>
              <g>
                <path d="M60,75.5c-6.341,0 -11.5,-5.159 -11.5,-11.5c0,-6.341 5.159,-11.5 11.5,-11.5c6.341,0 11.5,5.159 11.5,11.5c0,6.341 -5.159,11.5 -11.5,11.5z" fill="#3798A6"></path>
                <path d="M60,53c6.065,0 11,4.935 11,11c0,6.065 -4.935,11 -11,11c-6.065,0 -11,-4.935 -11,-11c0,-6.065 4.935,-11 11,-11M60,52c-6.627,0 -12,5.373 -12,12c0,6.627 5.373,12 12,12c6.627,0 12,-5.373 12,-12c0,-6.627 -5.373,-12 -12,-12z" fill="#3798A6"></path>
              </g>
              <g>
                <path d="M14,51.5c-6.341,0 -11.5,-5.159 -11.5,-11.5c0,-6.341 5.159,-11.5 11.5,-11.5c6.341,0 11.5,5.159 11.5,11.5c0,6.341 -5.159,11.5 -11.5,11.5z" fill="#3798A6"></path>
                <path d="M14,29c6.065,0 11,4.935 11,11c0,6.065 -4.935,11 -11,11c-6.065,0 -11,-4.935 -11,-11c0,-6.065 4.935,-11 11,-11M14,28c-6.627,0 -12,5.373 -12,12c0,6.627 5.373,12 12,12c6.627,0 12,-5.373 12,-12c0,-6.627 -5.373,-12 -12,-12z" fill="#3798A6"></path>
              </g>
            </g>
          </g>
        </svg>
        <span class="self-center ml-2 whitespace-nowrap">MasterCode</span>
      </a>
      <!-- <p class="p-0 m-0 mt-0" style="margin-left: 20px;">Master Code</p> -->
      <!-- <p class="ml-6 text-lg font-bold text-gray-800 dark:text-gray-200" href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newviewHome') ?>">

        Master Code

      </p> -->
    </div>

    <ul class="mt-6">

      <li class="relative px-6 py-3">
        <?php
        if ((isset($page) && $page == "dashboard")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 ml-2 rounded-tr-lg rounded-br-lg active" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('dash') ?>">
          <svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
            </path>
          </svg>
          <span class="ml-4">Dashboard</span>
        </a>
      </li>
    </ul>
    <ul>
      <li class="relative px-6 py-3">
        <?php
        if ((isset($page) && $page == "articles")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 ml-2 rounded-tr-lg rounded-br-lg active" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('Dashboard') ?>&action=<?= $this->datacrypt('articles') ?>">
          <svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01">
            </path>
          </svg>
          <span class="ml-4">Articles</span>
        </a>
      </li>
      <!-- <li class="relative px-6 py-3">
        <?php
        if ((isset($page) && $page == "editor")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('editor') ?>">
          <svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
          </svg>
          <span class="ml-4">Editeur</span>
        </a>
      </li> -->
      <?php if ($_SESSION["Auth"]["role"] === '0') : ?>
        <li class="relative px-6 py-3">
          <?php
          if ((isset($page) && $page == "message")) { ?>
            <span class="absolute inset-y-0 left-0 w-1 ml-2 rounded-tr-lg rounded-br-lg active" aria-hidden="true"></span>
          <?php } ?>
          <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('message') ?>">
            <svg class="inline-block w-6 h-6 fill-current" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M2 5a2 2 0 012-2h7a2 2 0 012 2v4a2 2 0 01-2 2H9l-3 3v-3H4a2 2 0 01-2-2V5z"></path>
              <path d="M15 7v2a4 4 0 01-4 4H9.828l-1.766 1.767c.28.149.599.233.938.233h2l3 3v-3h2a2 2 0 002-2V9a2 2 0 00-2-2h-1z">
              </path>
            </svg>
            <span class="ml-4">Message</span>
          </a>
        </li>
        <li class="relative px-6 py-3">
          <?php
          if ((isset($page) && $page == "categorie")) { ?>
            <span class="absolute inset-y-0 left-0 w-1 ml-2 rounded-tr-lg rounded-br-lg active" aria-hidden="true"></span>
          <?php } ?>
          <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('category') ?>">
            <svg class="inline-block w-6 h-6 fill-current" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM14 11a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1z">
              </path>
            </svg>
            <span class="ml-4">Catégorie</span>
          </a>
        </li>
        <li class="relative px-6 py-3">
          <?php
          if ((isset($page) && $page == "users")) { ?>
            <span class="absolute inset-y-0 left-0 w-1 ml-2 rounded-tr-lg rounded-br-lg active" aria-hidden="true"></span>
          <?php } ?>
          <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('users') ?>">
            <svg class="inline-block w-6 h-6 fill-current" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
              </path>
            </svg>
            <span class="ml-4">Users</span>
          </a>
        </li>
      <?php endif; ?>
      <li class="relative px-6 py-3">
        <?php
        if ((isset($page) && $page == "look")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 ml-2 rounded-tr-lg rounded-br-lg active" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newviewHome') ?>">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-5 h-5">
            <path d="M10 12.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5z" />
            <path fill-rule="evenodd" d="M.664 10.59a1.651 1.651 0 010-1.186A10.004 10.004 0 0110 3c4.257 0 7.893 2.66 9.336 6.41.147.381.146.804 0 1.186A10.004 10.004 0 0110 17c-4.257 0-7.893-2.66-9.336-6.41zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd" />
          </svg>
          <span class="ml-4">Voir le site</span>
        </a>
      </li>
      <li class="relative px-6 py-3">
        <?php
        if ((isset($page) && $page == "logout")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newLogout') ?>">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-5 h-5">
            <path fill-rule="evenodd" d="M3 4.25A2.25 2.25 0 015.25 2h5.5A2.25 2.25 0 0113 4.25v2a.75.75 0 01-1.5 0v-2a.75.75 0 00-.75-.75h-5.5a.75.75 0 00-.75.75v11.5c0 .414.336.75.75.75h5.5a.75.75 0 00.75-.75v-2a.75.75 0 011.5 0v2A2.25 2.25 0 0110.75 18h-5.5A2.25 2.25 0 013 15.75V4.25z" clip-rule="evenodd" />
            <path fill-rule="evenodd" d="M6 10a.75.75 0 01.75-.75h9.546l-1.048-.943a.75.75 0 111.004-1.114l2.5 2.25a.75.75 0 010 1.114l-2.5 2.25a.75.75 0 11-1.004-1.114l1.048-.943H6.75A.75.75 0 016 10z" clip-rule="evenodd" />
          </svg>
          <span class="ml-4">Deconnexion</span>
        </a>
      </li>

    </ul>
  </div>
</aside>
<!-- Mobile sidebar -->
<!-- Backdrop -->
<div x-show="isSideMenuOpen" x-transition:enter="transition ease-in-out duration-150" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-in-out duration-150" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" class="fixed inset-0 z-10 flex items-end bg-black bg-opacity-50 sm:items-center sm:justify-center"></div>
<aside class="fixed inset-y-0 z-20 flex-shrink-0 w-64 mt-16 overflow-y-auto bg-white dark:bg-gray-800 md:hidden" x-show="isSideMenuOpen" x-transition:enter="transition ease-in-out duration-150" x-transition:enter-start="opacity-0 transform -translate-x-20" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-in-out duration-150" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0 transform -translate-x-20" @click.away="closeSideMenu" @keydown.escape="closeSideMenu">
  <div class="py-4 text-gray-500 dark:text-gray-400">
    <a class="ml-6 text-lg font-bold text-gray-800 dark:text-gray-200" href="#">
      Master Code

    </a>
    <ul class="mt-6">
      <li class="relative px-6 py-3">
        <?php if ((isset($page) && $page == "dashboard")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold text-gray-800 transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200 dark:text-gray-100" href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('dash') ?>">
          <svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
            </path>
          </svg>
          <span class="ml-4">Dashboard</span>
        </a>
      </li>
    </ul>
    <ul>
      <li class="relative px-6 py-3">
        <?php if ((isset($page) && $page == "articles")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('articles') ?>">
          <svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2m-3 7h3m-3 4h3m-6-4h.01M9 16h.01">
            </path>
          </svg>
          <span class="ml-4">Articles</span>
        </a>
      </li>
      <!-- <li class="relative px-6 py-3">
      <?php if ((isset($page) && $page == "editor")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('editor') ?>">
          <svg class="w-5 h-5" aria-hidden="true" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
          </svg>
          <span class="ml-4">Editeur</span>
        </a>
      </li> -->
      <?php if ($_SESSION["Auth"]["role"] === '0') : ?>
        <li class="relative px-6 py-3">
          <?php if ((isset($page) && $page == "message")) { ?>
            <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
          <?php } ?>
          <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('message') ?>">
            <svg class="inline-block w-6 h-6 fill-current" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M2 5a2 2 0 012-2h7a2 2 0 012 2v4a2 2 0 01-2 2H9l-3 3v-3H4a2 2 0 01-2-2V5z"></path>
              <path d="M15 7v2a4 4 0 01-4 4H9.828l-1.766 1.767c.28.149.599.233.938.233h2l3 3v-3h2a2 2 0 002-2V9a2 2 0 00-2-2h-1z">
              </path>
            </svg>
            <span class="ml-4">Message</span>
          </a>
        </li>
        <li class="relative px-6 py-3">
          <?php if ((isset($page) && $page == "categorie")) { ?>
            <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
          <?php } ?>
          <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('category') ?>">
            <svg class="inline-block w-6 h-6 fill-current" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM14 11a1 1 0 011 1v1h1a1 1 0 110 2h-1v1a1 1 0 11-2 0v-1h-1a1 1 0 110-2h1v-1a1 1 0 011-1z">
              </path>
            </svg>
            <span class="ml-4">Categorie</span>
          </a>
        </li>
        <li class="relative px-6 py-3">
          <?php if ((isset($page) && $page == "users")) { ?>
            <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
          <?php } ?>
          <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('dashboard') ?>&action=<?= $this->datacrypt('Users') ?>">
            <svg class="inline-block w-6 h-6 fill-current" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <path d="M13 6a3 3 0 11-6 0 3 3 0 016 0zM18 8a2 2 0 11-4 0 2 2 0 014 0zM14 15a4 4 0 00-8 0v3h8v-3zM6 8a2 2 0 11-4 0 2 2 0 014 0zM16 18v-3a5.972 5.972 0 00-.75-2.906A3.005 3.005 0 0119 15v3h-3zM4.75 12.094A5.973 5.973 0 004 15v3H1v-3a3 3 0 013.75-2.906z">
              </path>
            </svg>
            <span class="ml-4">Users</span>
          </a>
        </li>
      <?php endif; ?>
      <li class="relative px-6 py-3">
        <?php if ((isset($page) && $page == "look")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newviewHome') ?>">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-5 h-5">
            <path d="M10 12.5a2.5 2.5 0 100-5 2.5 2.5 0 000 5z" />
            <path fill-rule="evenodd" d="M.664 10.59a1.651 1.651 0 010-1.186A10.004 10.004 0 0110 3c4.257 0 7.893 2.66 9.336 6.41.147.381.146.804 0 1.186A10.004 10.004 0 0110 17c-4.257 0-7.893-2.66-9.336-6.41zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clip-rule="evenodd" />
          </svg>
          <span class="ml-4">Voir le site</span>
        </a>
      </li>
      <li class="relative px-6 py-3">
        <?php if ((isset($page) && $page == "logout")) { ?>
          <span class="absolute inset-y-0 left-0 w-1 bg-purple-600 rounded-tr-lg rounded-br-lg" aria-hidden="true"></span>
        <?php } ?>
        <a class="inline-flex items-center w-full text-sm font-semibold transition-colors duration-150 hover:text-gray-800 dark:hover:text-gray-200" href="?goto=<?= $this->datacrypt('home') ?>&action=<?= $this->datacrypt('newLogout') ?>">
          <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="inline-block w-5 h-5">
            <path fill-rule="evenodd" d="M3 4.25A2.25 2.25 0 015.25 2h5.5A2.25 2.25 0 0113 4.25v2a.75.75 0 01-1.5 0v-2a.75.75 0 00-.75-.75h-5.5a.75.75 0 00-.75.75v11.5c0 .414.336.75.75.75h5.5a.75.75 0 00.75-.75v-2a.75.75 0 011.5 0v2A2.25 2.25 0 0110.75 18h-5.5A2.25 2.25 0 013 15.75V4.25z" clip-rule="evenodd" />
            <path fill-rule="evenodd" d="M6 10a.75.75 0 01.75-.75h9.546l-1.048-.943a.75.75 0 111.004-1.114l2.5 2.25a.75.75 0 010 1.114l-2.5 2.25a.75.75 0 11-1.004-1.114l1.048-.943H6.75A.75.75 0 016 10z" clip-rule="evenodd" />
          </svg>
          <span class="ml-4">Deconnexion</span>
        </a>
      </li>

    </ul>

  </div>
</aside>